# Generated by Django 5.1 on 2024-08-08 06:56

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExampleModel',
            fields=[
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
            ],
        ),
    ]
